### ISSUE TITLE
2.0.5 dist folder doesen't transform！！

### ISSUE THREAD

**Issue by k186** [zadzbw/koa2-cors#2]
dist folder file is same with src fix it , 

return async function (ctx, next) {
               ^^^^^^^^
SyntaxError: Unexpected token function

哥们 dist 目录的文件没bable 转译

**Comment by zadzbw** [comment]
@k186 
你的node版本是多少？
koa2需要node >= v7.6.0，高于这个版本的node是默认支持async语法的

**Comment by k186** [comment]
@zadzbw node是6.10.0 目前锁定koa-cors 2.0.4的版本，我没用koa2 用的koa,应该是这个原因
 "koa": "2.3.0",
    "koa2-cors": "2.0.4",
    "koa2-static": "1.0.1"

**Comment by zadzbw** [comment]
@k186 
koa2就是koa的v2版，从你的package.json来看，你用的就是koa2啊，
你是把你项目的入口文件用babel编译过了？不然6.10.0是跑不起来koa2的啊

**Comment by k186** [comment]
@zadzbw 开发环境 是用bable 跑的 然后 发包的时候用 babel转了一次，我现在那个包是要全局跑，所以安全使用就要用node 7.6以上,我后期把这个判断加一下就可以了，目前就用2.0.4的编译过的版本

**Comment by zadzbw** [comment]
@k186 
恩 可以先使用2.0.4的，等升级到node7.6以后，就能不用babel编译直接使用async语法了
