### ISSUE TITLE
Is it safe to use the headers from Access-Control-Request-Headers if the allowHeaders is empty?

### ISSUE THREAD

**Issue by LvChengbin** [zadzbw/koa2-cors#3]
I found the code below:
```
if (options.allowHeaders) {
        ctx.set('Access-Control-Allow-Headers', options.allowHeaders.join(','));
      } else {
        ctx.set('Access-Control-Allow-Headers', ctx.get('Access-Control-Request-Headers'));
      }
}
```

And  I have a question of that if it is safe to use the value of `Access-Control-Request-Headers` for `Access-Control-Allow-Headers` or maybe I misunderstand the usage of the `Access-Control-Request-Headers`.

**Comment by zadzbw** [comment]
@LvChengbin 

在预检请求里，`Access-Control-Request-Headers` 字段和 `Access-Control-Request-Method` 字段的作用类似，用于告知服务器这个请求所携带的自定义 header，然后服务器会根据此判断请求是否被允许，所以在 `options.allowHeaders` 未指定时，会使用 `Access-Control-Request-Headers` 的值作为 `Access-Control-Allow-Headers` 的值。

我认为这个字段只是表明请求携带的自定义 header，所以是安全的。

**Comment by fjeddy** [comment]
Excellent, replying in chinese to an english question. Your answer was really helpful, now the entire world understands you.
