### ISSUE TITLE
How to set up multiple origin?

### ISSUE THREAD

**Issue by atjiu** [zadzbw/koa2-cors#4]
```js
app.use(cors({
  origin: 'http://localhost:8080'
}));
```

This setting is no problem on the localhost:8080 service.

But I also want to configure a service on the 8081 port should be configured?

**Comment by zadzbw** [comment]
@tomoya92 
multiple origins are not allowed, so set origin to 'http://localhost:8080, http://localhost:8081, ...etc' is can't run, and you can set origin to a function.

```js
app.use(cors({
  origin: function (ctx) {
    const requestOrigin = ctx.get('Origin');
    const yourWhiteList = ['http://localhost:8080', 'http://localhost:8081', 'xxx'];
    if (yourWhiteList.includes(requestOrigin)) {
      return requestOrigin;
    }
    return false;
  },
}));
```

**Comment by atjiu** [comment]
@zadzbw thx
